### PR TITLE
Onboarding for GCcollab

### PR DESCRIPTION
**Pull request by ethanWallace**
Converted to accept different user types(public servants, students and academics).

### CODE REVIEW

**Comment by sdkibb** [comment]
@markwooff We will need to merge this tomorrow. @ethanWallace will you be in to help with testing on production? I'm sure it will work fine but...

**Comment by ToferC** [comment]
I think onboarding is suggesting people who are already colleagues.

**Comment by sdkibb** [comment]
It was good for me but we will keep testing and confirm. So, on the suggestion it showed a member and the button below said already a colleague?

**Comment by ToferC** [comment]
Nope. Said not colleague, but Sean boots, Kent Aitkin, Sébastien and folks
I'm pretty sure are already colleagues.

**Comment by sdkibb** [comment]
Ok, the testing we've done it seemed to work fine but we will continue to check this component of the release out.  We did fix a few issues. We will continue to fix some issues tonight but I don't see any show stoppers. We've officially launched Onboarding to GCcollab :)

**Comment by ToferC** [comment]
Way to go, team!

**Pull request merged**
