### PR TITLE
Created new API for member data

### PR DESCRIPTION
**Pull request by markwooff**
Also added new charts to display dashboard stats

### CODE REVIEW

**Comment by sdkibb** [comment]
Beauty.

**Comment by markwooff** [comment]
@sdkibb there are a few new API endpoints that have been created for this data.. can walk you through them but they are all based off this URL:

https://gccollab.ca/services/api/rest/json/?method=member.stats&type=all

where the `type` can be set to `all`, `federal`, `provincial`, `student`, `academic`, `university` or `college`

**Comment by sdkibb** [comment]
OK. Was there an API that already existed for this created in GCconnex? 

I'm still going to keep with the .NET wrapper in anticipation of more systems landing in the cloud and having a single source to retrieve the open data for all GC collaborative platforms.

**Comment by markwooff** [comment]
Nah but there is an existing function within Elgg to expose web services using the `elgg_ws_expose_function()` function within the `start.php` plugin file. Figured it'd be easy to get individual user type stats this way. Your API is still needed for the timeline chart!

**Pull request merged**
